### ISSUE TITLE
Prettier isn't working well

### ISSUE THREAD

**Issue by JCKodel** [UnwrittenFun/svelte-vscode#87] opened 2019-11-04 18:57 UTC
This:
```html
<h1>Hello <span>{name}</span>!</h1>
```

is formatted into this:
```html
<h1>
  Hello
  <span>{name}</span>
  !
</h1>
```

Which is wrong (because line breaks are turned into white space, leaving an space between {name} and !.

**Comment by jbg** [comment] 2019-11-27 17:57
Duplicate of #82

**Closed as completed** 2020-05-06 19:44 UTC
