### ISSUE TITLE
Pressing enter after creating a CSS rule adds an attribute instead of going to the next line

### ISSUE THREAD

**Issue by pjdon** [UnwrittenFun/svelte-vscode#45] opened 2019-05-19 21:53 UTC
**Steps:**
1. Within a `style` scope inside of a `.svelte` file, add a CSS rule (e.g. `p {`)
2. Press `Enter`

**Expected:**
Cursor will move to the next line and create a block like:
```
p {

}
```

**Actual Result:**
Adds the first CSS attribute rule:
```
p {align-content: }
```

**Workaround:**
Press `Escape`, then `Enter`

It's not a huge issue, but the behavior is counter to how VSCode usually works with CSS files.

**Comment by arxpoetica** [comment] 2019-06-04 04:42
Just watching this one, it's happening on my end too.

![Example](http://g.recordit.co/NNZ4HQiaq1.gif)

**Comment by ricardosaiz** [comment] 2019-06-05 21:54
Same for me! My workaround is `shift + enter` insted of `esc - enter`

**Comment by benjaminbenais** [comment] 2019-07-05 14:28
Same unexpected behaviour for me. Is there any place in VS code to fix this ?

**Comment by anttti** [comment] 2019-08-06 13:46
The only "fix" I've been able to come up with is disabling enter for accepting autocomplete, instead I've been learning to autocomplete with tab. It's tough when hitting enter is so deep in muscle memory :-)

**Comment by theschmocker** [comment] 2019-09-08 17:05
It looks like this is happening because completion is being triggered immediately after '{' is pressed. [Here's the line in the language server config](https://github.com/UnwrittenFun/svelte-language-server/blob/f4c8141a9e21a972b25514a646292032901926ae/src/server.ts#L63). 

Removing the brackets from `triggerCharacters` fixed the issue for me. 

I created an issue and a PR on the language server: https://github.com/UnwrittenFun/svelte-language-server/issues/27

**Comment by rob-balfre** [comment] 2019-09-22 06:45
Anyone else still seeing this?

**Comment by theschmocker** [comment] 2019-09-22 17:36
That PR was merged, but it doesn't look like there's been a new release since before then

**Comment by rob-balfre** [comment] 2019-09-22 21:18
Strange the repo (v0.9.1) seems to be behind the current VSCode release (v0.9.2)

**Comment by jamesbirtles** [comment] 2019-10-06 12:13
@theschmocker's fix was released in 0.9.3

**Closed as completed by jamesbirtles** 2019-10-06 12:13 UTC
Labels: bug
