### ISSUE TITLE
Errors not properly shown in Visual Studio Code

### ISSUE THREAD

**Issue by fkereki** [UnwrittenFun/svelte-vscode#63] opened 2019-07-22 23:41 UTC
When editing code in Visual Studio Code, errors show as three small dots, instead of a red block at the right as usual. This is quite hard to read and recognize; there's no quick way of seeing if there are any problems in the code.

![Screenshot_20190722_203955](https://user-images.githubusercontent.com/2468063/61672179-0986b700-acc1-11e9-91da-f5585fe11791.png)

**Comment by alixaxel** [comment] 2019-08-09 22:15
I've seen this as well, related to https://github.com/UnwrittenFun/svelte-vscode/issues/65

**Comment by jamesbirtles** [comment] 2019-10-07 12:46
Typically these three dots aren't explicitly errors, so much as suggestions. For example, on the export it likely says something like `name implicitly has any type`. This is a typescript error being but as you're not using typescript it can't really be sure/enforce anything there so it appears as three dots.

Hope this helps. Closing this as working as intended

**Closed as completed by jamesbirtles** 2019-10-07 12:46 UTC
